export const ENUM_LOADING = 'ENUM_LOADING';
export const ENUM_LOADING_SENDING = 'ENUM_LOADING_SENDING';
export const ENUM_LOADING_SUCCESS = 'ENUM_LOADING_SUCCESS';
export const ENUM_LOADING_FAILED = 'ENUM_LOADING_FAILED';
